/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import BO.Product;
import BO.Productcategory;
import BO.Productline;
import BO.Taxrate;
import Services.ProdCatService;
import Services.ProdLineService;
import Services.ProductService;
import Services.TaxrateService;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Temp
 */
public class FrmMain extends javax.swing.JFrame {

    private CardLayout layCard;

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        layCard = new CardLayout();
        mainPanel.setLayout(layCard);
        mainPanel.add("Products", pnlProductList);
        populateProductList();
        populateProductComboBoxes();
        mainPanel.add("Tax", pnlTaxRates);
        mainPanel.add("Lines", pnlProductLines);
        mainPanel.add("Categories", pnlProductCategories);

    }

    private void Showpanel(String panelname) {
        layCard.show(mainPanel, panelname);
        switch (panelname) {
            case "Products":
                populateProductList();
                break;
            case "Tax":
                populateTaxlist();
                break;
            case "Lines":
                break;
            case "Categories":
                break;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jFrame1 = new javax.swing.JFrame();
        HerbDerpPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("HerbDerpPU").createEntityManager();
        productQuery = java.beans.Beans.isDesignTime() ? null : HerbDerpPUEntityManager.createQuery("SELECT p FROM Product p");
        productList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : productQuery.getResultList();
        productQuery1 = java.beans.Beans.isDesignTime() ? null : HerbDerpPUEntityManager.createQuery("SELECT p FROM Product p");
        productList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : productQuery1.getResultList();
        productQuery2 = java.beans.Beans.isDesignTime() ? null : HerbDerpPUEntityManager.createQuery("SELECT p FROM Product p");
        productList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : productQuery2.getResultList();
        mainPanel = new javax.swing.JPanel();
        pnlTaxRates = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTaxrates = new javax.swing.JList();
        btnRemove = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTaxrate = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pnlProductLines = new javax.swing.JPanel();
        pnlProductCategories = new javax.swing.JPanel();
        pnlProductList = new javax.swing.JPanel();
        txtSKU = new javax.swing.JTextField();
        txtProdPrice = new javax.swing.JTextField();
        txtProdDesc = new javax.swing.JTextField();
        txtProdName = new javax.swing.JTextField();
        txtProdCat = new javax.swing.JTextField();
        txtProdLine = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstProducts = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox();
        cmbLine = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jmenMainBar = new javax.swing.JMenuBar();
        jmenProducts = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jmenClients = new javax.swing.JMenu();
        jmenUsers = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 0));
        mainPanel.setToolTipText("");
        mainPanel.setLayout(new java.awt.CardLayout());

        pnlTaxRates.setBackground(new java.awt.Color(204, 204, 204));

        lstTaxrates.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstTaxrates.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstTaxratesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstTaxrates);

        btnRemove.setText("Verwijderen");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        jLabel1.setText("Taxrate");

        btnSave.setText("Opslaan");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel2.setText("Taxrates");

        javax.swing.GroupLayout pnlTaxRatesLayout = new javax.swing.GroupLayout(pnlTaxRates);
        pnlTaxRates.setLayout(pnlTaxRatesLayout);
        pnlTaxRatesLayout.setHorizontalGroup(
            pnlTaxRatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaxRatesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTaxRatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTaxRatesLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addGroup(pnlTaxRatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTaxRatesLayout.createSequentialGroup()
                                .addComponent(txtTaxrate, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSave))
                            .addComponent(jLabel1))))
                .addContainerGap(436, Short.MAX_VALUE))
        );
        pnlTaxRatesLayout.setVerticalGroup(
            pnlTaxRatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaxRatesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTaxRatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTaxRatesLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlTaxRatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTaxrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSave))))
                .addGap(18, 18, 18)
                .addComponent(btnRemove)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        mainPanel.add(pnlTaxRates, "card3");

        pnlProductLines.setBackground(new java.awt.Color(153, 153, 0));

        javax.swing.GroupLayout pnlProductLinesLayout = new javax.swing.GroupLayout(pnlProductLines);
        pnlProductLines.setLayout(pnlProductLinesLayout);
        pnlProductLinesLayout.setHorizontalGroup(
            pnlProductLinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 859, Short.MAX_VALUE)
        );
        pnlProductLinesLayout.setVerticalGroup(
            pnlProductLinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        mainPanel.add(pnlProductLines, "card4");

        pnlProductCategories.setBackground(new java.awt.Color(0, 255, 204));

        javax.swing.GroupLayout pnlProductCategoriesLayout = new javax.swing.GroupLayout(pnlProductCategories);
        pnlProductCategories.setLayout(pnlProductCategoriesLayout);
        pnlProductCategoriesLayout.setHorizontalGroup(
            pnlProductCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 859, Short.MAX_VALUE)
        );
        pnlProductCategoriesLayout.setVerticalGroup(
            pnlProductCategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        mainPanel.add(pnlProductCategories, "card5");

        txtSKU.setText("SKU");

        txtProdPrice.setText("ProdPrice");

        txtProdDesc.setText("ProdDesc");

        txtProdName.setText("ProdName");

        txtProdCat.setText("ProdCategory");

        txtProdLine.setText("ProdLine");

        lstProducts.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstProducts.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstProductsValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstProducts);

        jLabel3.setText("SKU");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel4.setText("Line:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel5.setText("Description:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel6.setText("Name:");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel7.setText("Category:");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel8.setText("Price:");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel9.setText("Euro");

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCategory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCategoryItemStateChanged(evt);
            }
        });

        cmbLine.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbLine.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbLineItemStateChanged(evt);
            }
        });

        jLabel10.setText("Category Filter");

        jLabel11.setText("Line Filter");

        javax.swing.GroupLayout pnlProductListLayout = new javax.swing.GroupLayout(pnlProductList);
        pnlProductList.setLayout(pnlProductListLayout);
        pnlProductListLayout.setHorizontalGroup(
            pnlProductListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlProductListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductListLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(pnlProductListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlProductListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlProductListLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlProductListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProductListLayout.createSequentialGroup()
                        .addGroup(pnlProductListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtProdLine, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSKU, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProdName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addGroup(pnlProductListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(cmbCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlProductListLayout.createSequentialGroup()
                        .addGroup(pnlProductListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProdDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProdCat, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlProductListLayout.createSequentialGroup()
                                .addComponent(txtProdPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbLine, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlProductListLayout.setVerticalGroup(
            pnlProductListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductListLayout.createSequentialGroup()
                .addGroup(pnlProductListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductListLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(pnlProductListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSKU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(pnlProductListLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(pnlProductListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlProductListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtProdLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtProdDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlProductListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProdCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProdPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlProductListLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );

        mainPanel.add(pnlProductList, "card2");

        jmenProducts.setText("Products");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem1.setText("Product List");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmenProducts.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem2.setText("TaxRates");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jmenProducts.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem3.setText("Product Lines");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jmenProducts.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem4.setText("Product Categories");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jmenProducts.add(jMenuItem4);

        jmenMainBar.add(jmenProducts);

        jmenClients.setText("Clients");
        jmenMainBar.add(jmenClients);

        jmenUsers.setText("Users");
        jmenMainBar.add(jmenUsers);

        setJMenuBar(jmenMainBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Showpanel("Products");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Showpanel("Tax");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Showpanel("Lines");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Showpanel("Categories");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (lstTaxrates.getSelectedIndex() >= 0) {
            UpdateTaxrate();
        } else {
            SaveTaxRate();
        }

        populateTaxlist();

    }//GEN-LAST:event_btnSaveActionPerformed

    private void lstTaxratesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstTaxratesValueChanged
        if (lstTaxrates.getSelectedIndex() >= 0) {
            Taxrate selectedTax = (Taxrate) lstTaxrates.getSelectedValue();
            txtTaxrate.setText(selectedTax.getTaxrate().toString());
            System.out.println(selectedTax.getId().toString());
        }
    }//GEN-LAST:event_lstTaxratesValueChanged

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        DeleteItem();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void lstProductsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstProductsValueChanged
        if (lstProducts.getSelectedIndex() >= 0) {
            FillProductTextboxes((Product) lstProducts.getSelectedValue());
        }
    }//GEN-LAST:event_lstProductsValueChanged

    private void cmbCategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCategoryItemStateChanged
        if (cmbCategory.getSelectedIndex() >= 0) {
            if (cmbCategory.getSelectedItem().equals("All")) {
                populateProductList();
            }
            else {
            populateProductList((Productcategory) cmbCategory.getSelectedItem());
            }
        }
    }//GEN-LAST:event_cmbCategoryItemStateChanged

    private void cmbLineItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbLineItemStateChanged
        if (cmbLine.getSelectedIndex() >= 0) {
            if (cmbLine.getSelectedItem().equals("All")) {
                populateProductList();
            }
            else {
                populateProductList((Productline) cmbLine.getSelectedItem());
            }
        }
    }//GEN-LAST:event_cmbLineItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager HerbDerpPUEntityManager;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbCategory;
    private javax.swing.JComboBox cmbLine;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JMenu jmenClients;
    private javax.swing.JMenuBar jmenMainBar;
    private javax.swing.JMenu jmenProducts;
    private javax.swing.JMenu jmenUsers;
    private javax.swing.JList lstProducts;
    private javax.swing.JList lstTaxrates;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pnlProductCategories;
    private javax.swing.JPanel pnlProductLines;
    private javax.swing.JPanel pnlProductList;
    private javax.swing.JPanel pnlTaxRates;
    private java.util.List<BO.Product> productList;
    private java.util.List<BO.Product> productList1;
    private java.util.List<BO.Product> productList2;
    private javax.persistence.Query productQuery;
    private javax.persistence.Query productQuery1;
    private javax.persistence.Query productQuery2;
    private javax.swing.JTextField txtProdCat;
    private javax.swing.JTextField txtProdDesc;
    private javax.swing.JTextField txtProdLine;
    private javax.swing.JTextField txtProdName;
    private javax.swing.JTextField txtProdPrice;
    private javax.swing.JTextField txtSKU;
    private javax.swing.JTextField txtTaxrate;
    // End of variables declaration//GEN-END:variables

    private void populateTaxlist() {
        TaxrateService tservice = new TaxrateService();
        List<Taxrate> taxr = tservice.getAllTaxrates();
        DefaultListModel defList = new DefaultListModel();
        for (Taxrate taxr1 : taxr) {
            defList.addElement(taxr1);
        }
        lstTaxrates.setModel(defList);
    }

    private void SaveTaxRate() {
        TaxrateService tservice = new TaxrateService();
        Taxrate newTax = new Taxrate();
        newTax.setTaxrate(Double.parseDouble(txtTaxrate.getText()));
        tservice.Save(newTax);
        populateTaxlist();
    }

    private void UpdateTaxrate() {
        TaxrateService tservice = new TaxrateService();
        Taxrate updateTax = (Taxrate) lstTaxrates.getSelectedValue();
        updateTax.setTaxrate(Double.parseDouble(txtTaxrate.getText()));
        tservice.Save(updateTax);
        populateTaxlist();
    }

    private void DeleteItem() {
        TaxrateService tservice = new TaxrateService();
        Taxrate deleteTax = (Taxrate) lstTaxrates.getSelectedValue();
        int showConfirmDialog = JOptionPane.showConfirmDialog(pnlTaxRates, "Wilt u deze taxrate verwijderen?");
        if (showConfirmDialog == JOptionPane.YES_OPTION) {
            tservice.Delete(deleteTax);
        }
        populateTaxlist();
        lstTaxrates.setSelectedIndex(1);
    }

    private void populateProductList() {
        ProductService prodserv = new ProductService();
        List<Product> products = prodserv.GetAllProducts();
        DefaultListModel defList = new DefaultListModel();
        for (Product p : products) {
            defList.addElement(p);
        }
        lstProducts.setModel(defList);
    }

    private void populateProductList(Productcategory pc) {
        ProductService prodserv = new ProductService();
        List<Product> products = prodserv.GetAllProducts();
        DefaultListModel defList = new DefaultListModel();
        for (Product p : products) {
            if (p.getProductcategoryidId().getId() == pc.getId()) {
                defList.addElement(p);
            }
        };
        lstProducts.setModel(defList);
    }
    
    private void populateProductList(Productline pl) {
        ProductService productService = new ProductService();
        List<Product> products = productService.GetAllProducts();
        DefaultListModel defList = new DefaultListModel();
        for (Product p : products) {
            if (p.getProductlineidId().getId() == pl.getId()) {
                defList.addElement(defList);
            }
        }
    }

    private void FillProductTextboxes(Product product) {
        txtProdCat.setText(product.getProductcategoryidId().getProductcategoryname());
        txtProdDesc.setText(product.getProductdescription());
        txtProdLine.setText(product.getProductlineidId().getLinename());
        txtProdName.setText(product.getProductname());
        txtProdPrice.setText(product.getProductprice().toString());
        txtSKU.setText(product.getSku());
    }

    private void populateProductComboBoxes() {
        cmbCategory.removeAllItems();
        cmbLine.removeAllItems();
        ProdCatService prodcat = new ProdCatService();
        ProdLineService prodline = new ProdLineService();
        List<Productcategory> prodcats = prodcat.getAllCategories();
        List<Productline> prodlines = prodline.GetAllProdLines();
        
        cmbLine.addItem("All");
        for (Productline pl : prodlines) {
            cmbLine.addItem(pl);
        }
        
        cmbCategory.addItem("All");
        for (Productcategory pc : prodcats) {
            cmbCategory.addItem(pc);
        }

    }
}
